Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.groep.L.Domain;
using ASP.groep.L.Infrastructure.Contexts;
using System.Diagnostics;
using MediatR;
using ASP.groep.L.Application.CQRS.Commands;
using ASP.groep.L.Application.CQRS.Queries;
using AutoMapper;
using ASP.groep.L.Application.FileManagement;
using ASP.groep.L.Application.Extensions;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Data.SqlClient.Server;
using Microsoft.Net.Http.Headers;
using System.Globalization;
using System.IO.Compression;
using System.Net;
using ASP.groep.L.AdminMVC.Utilities;
using Microsoft.AspNetCore.Authorization;

namespace ASP.groep.L.Controllers
{
    [Authorize(Roles = "MVC Admin")]
    public class SiteController : Controller
    {
        private IMediator _mediator;
        private IMapper _mapper;
        public SiteController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(GetAllSitesQuery query)
        {
            return View(await _mediator.Send(query));
        }

        public async Task<IActionResult> Details(int? id)
        {
            var query = new GetSiteDetailQuery();
            query.Id = (int)id;
            var site = await _mediator.Send(query);
            return View(site);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["TreeFarmId"] = new SelectList(await _mediator.Send(new GetAllTreeFarmsQuery()), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,BluePrint,ImageFile,TreeFarm,TreeFarmId,Address")] Site site)
        {
            if (site.ImageFile != null)
            {
                Stream image = site.ImageFile.OpenReadStream();
                byte[] bytes = new byte[site.ImageFile.Length];
                image.Read(bytes, 0, (int)site.ImageFile.Length);
                var memoryStream = new MemoryStream(bytes);
                site.BluePrint = await FileManagement.UploadImage(memoryStream, site.ImageFile.FileName);
                site.BluePrintName = site.ImageFile.FileName;
            }
            var command = new CreateSiteCommand();
            command.Site = site;
            await _mediator.Send(command);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id, GetSiteByIdQuery query)
        {
            ViewData["TreeFarmId"] = new SelectList(await _mediator.Send(new GetAllTreeFarmsQuery()), "Id", "Name");
            query.Id = (int)id;
            var site = await _mediator.Send(query);
            return View(site);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([Bind("Id,Name,Description,BluePrint,ImageFile,TreeFarm,TreeFarmId,Address")] Site site)
        {
            if (site.ImageFile != null)
            {
                Stream image = site.ImageFile.OpenReadStream();
                byte[] bytes = new byte[site.ImageFile.Length];
                image.Read(bytes, 0, (int)site.ImageFile.Length);
                var memoryStream = new MemoryStream(bytes);
                site.BluePrint = await FileManagement.UploadImage(memoryStream, site.ImageFile.FileName);
                site.BluePrintName = site.ImageFile.FileName;
            }

            var command = new UpdateSiteCommand();
            command.Site = site;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var query = new GetSiteByIdQuery();
            query.Id = (int)id;
            var site = await _mediator.Send(query);
            return View(_mapper.Map<Site>(site));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            DeleteSiteCommand command = new DeleteSiteCommand();
            command.Id = id;
            var query = new GetSiteByIdQuery();
            query.Id = (int)id;
            var site = await _mediator.Send(query);
            if (site.BluePrintName != null && site.BluePrintName != "")
            {
                await FileManagement.DeleteImage(site.BluePrintName);
            }

            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> SiteExists(int id)
        {
            var query = new GetSiteByIdQuery();
            query.Id = id;
            var site = await _mediator.Send(query);

            return false;
        }
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Controllers/TreeSpeciesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ASP.groep.L.Domain;
using MediatR;
using ASP.groep.L.Application.CQRS.Commands;
using ASP.groep.L.Application.CQRS.Queries;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using ASP.groep.L.Application.FileManagement;
using ASP.groep.L.Application.Extensions;

namespace ASP.groep.L.Controllers
{
    [Authorize(Roles = "MVC Admin,MVC Planner")]
    public class TreeSpeciesController : Controller
    {
        private IMediator _mediator;
        private IMapper _mapper;
        public TreeSpeciesController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(GetAllTreeSpeciesQuery query)
        {
            return View(await _mediator.Send(query));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetTreeSpeciesByIdQuery();
            query.Id = (int)id;
            var TreeSpecies = await _mediator.Send(query);
            if (TreeSpecies == null)
            {
                return NotFound();
            }

            return View(TreeSpecies);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["MaintenancePlanID"] = new SelectList(await _mediator.Send(new GetAllMaintenancePlansQuery()), "Id", "Title");
            ViewData["Zone"] = new SelectList(await _mediator.Send(new GetAllZonesQuery()), "Id", "Name");
            ViewData["Season"] = new SelectList(Enum.GetValues(typeof(Season)));
            return View();
        }

        [Authorize(Roles = "MVC Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,PicturePath,ImageFile,MaintenancePlanID,MaintenancePlan")] TreeSpecies treeSpecies)
        {
            
            if (treeSpecies.ImageFile != null)
            {
                Stream image = treeSpecies.ImageFile.OpenReadStream();
                byte[] bytes = new byte[treeSpecies.ImageFile.Length];
                image.Read(bytes, 0, (int)treeSpecies.ImageFile.Length);
                var memoryStream = new MemoryStream(bytes);
                treeSpecies.ImageName = treeSpecies.ImageFile.FileName;
                treeSpecies.PicturePath = await FileManagement.UploadImage(memoryStream, treeSpecies.ImageName);
            }
            if (String.IsNullOrEmpty(treeSpecies.MaintenancePlan.Link) && treeSpecies.MaintenancePlan.PlanFile != null)
            {
                Stream image = treeSpecies.MaintenancePlan.PlanFile.OpenReadStream();
                byte[] bytes = new byte[treeSpecies.MaintenancePlan.PlanFile.Length];
                image.Read(bytes, 0, (int)treeSpecies.MaintenancePlan.PlanFile.Length);
                var memoryStream = new MemoryStream(bytes);
                treeSpecies.MaintenancePlan.FileName = treeSpecies.MaintenancePlan.PlanFile.FileName;
                treeSpecies.MaintenancePlan.Link = await FileManagement.UploadPDF(memoryStream, treeSpecies.MaintenancePlan.FileName);
                var mem = GenerateQRCode.GenerateQR(treeSpecies.MaintenancePlan.Link);
                treeSpecies.MaintenancePlan.QRCodeName = "QRCode" + treeSpecies.MaintenancePlan.Id + treeSpecies.MaintenancePlan.Season.ToString() + new Random().Next(0, 100);
                treeSpecies.MaintenancePlan.QRCode = await FileManagement.UploadImage(mem, treeSpecies.MaintenancePlan.QRCodeName);
            }


            var command = new CreateTreeSpeciesCommand();
            command.TreeSpecies = treeSpecies;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "MVC Admin")]
        public async Task<IActionResult> Update(int? id, GetTreeSpeciesByIdQuery query)
        {
            query.Id = (int)id;
            var TreeSpecies = await _mediator.Send(query);
            if (TreeSpecies == null)
            {
                return NotFound();
            }
            ViewData["MaintenancePlanID"] = new SelectList(await _mediator.Send(new GetAllMaintenancePlansQuery()), "Id", "Title");
            ViewData["Zone"] = new SelectList(await _mediator.Send(new GetAllZonesQuery()), "Id", "Name");
            ViewData["Season"] = new SelectList(Enum.GetValues(typeof(Season)));
            return View(TreeSpecies);
        }
        [Authorize(Roles = "MVC Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("Id,Name,Description,PicturePath,ImageFile,MaintenancePlanID,MaintenancePlan")] TreeSpecies treeSpecies)
        {
            if (treeSpecies.ImageFile!=null)
            {
                Stream image = treeSpecies.ImageFile.OpenReadStream();
                byte[] bytes = new byte[treeSpecies.ImageFile.Length];
                image.Read(bytes, 0, (int)treeSpecies.ImageFile.Length);
                var memoryStream = new MemoryStream(bytes);
                treeSpecies.ImageName = treeSpecies.ImageFile.FileName;
                treeSpecies.PicturePath = await FileManagement.UploadImage(memoryStream, treeSpecies.ImageName);
            }
            var command = new UpdateTreeSpeciesCommand();
            command.TreeSpecies = treeSpecies;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "MVC Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetTreeSpeciesByIdQuery();
            query.Id = (int)id;
            var TreeSpecies = await _mediator.Send(query);
            if (TreeSpecies == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<TreeSpecies>(TreeSpecies));
        }

        [Authorize(Roles = "MVC Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            DeleteTreeSpeciesCommand command = new DeleteTreeSpeciesCommand();
            command.Id = id;
            var query = new GetTreeSpeciesByIdQuery();
            query.Id = (int)id;
            var treeSpecies = await _mediator.Send(query);
            if (!String.IsNullOrEmpty(treeSpecies.PicturePath)&& !String.IsNullOrEmpty(treeSpecies.ImageName))
            {
                await FileManagement.DeleteImage(treeSpecies.ImageName);

            }
            if (!String.IsNullOrEmpty(treeSpecies.MaintenancePlan.FileName) && !String.IsNullOrEmpty(treeSpecies.MaintenancePlan.QRCodeName))
            {
                await FileManagement.DeletePDF(treeSpecies.MaintenancePlan.FileName);
                await FileManagement.DeleteImage(treeSpecies.MaintenancePlan.QRCodeName);
            }

            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> TreeSpeciesExists(int id)
        {
            if (id == null)
            {
                return false;
            }
            var query = new GetTreeSpeciesByIdQuery();
            query.Id = id;
            var TreeSpecies = await _mediator.Send(query);
            if (TreeSpecies != null)
            {
                return true;
            }
            return false;
        }
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Controllers/UserController.cs
using ASP.groep.L.Application.CQRS.DTOS;
using ASP.groep.L.Application.CQRS.Queries;
using ASP.groep.L.Domain;
using Microsoft.AspNetCore.Mvc;
using ASP.groep.L.Application.CQRS.Commands;
using MediatR;
using AutoMapper;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.groep.L.Controllers
{
    [Authorize(Roles = "MVC Admin")]
    public class UserController : Controller
    {
        IMediator _mediator;
        public UserController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("Index")]
        public async Task<IActionResult> Index(Role role)
        {
            GetAllUsersQuery query = new GetAllUsersQuery();
            IEnumerable<User> Users = await _mediator.Send(query);
            if (role == Role.Ionic_Employee)
            {
                return View("Employees",Users.Where<User>(u => u.Role == role));
            }
            return View("Planners", Users.Where<User>(u => u.Role == role));
        }

        [HttpGet]
        public IActionResult Create(Role role)
        {
            ViewData["CurRole"] = role;
            ViewData["Role"] = new SelectList(Enum.GetValues(typeof(Role)));
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(User user)
        {
            var command = new CreateUserCommand();
            command.User = user;
            _mediator.Send(command);
            return RedirectToAction(nameof(Index), new { role = user.Role });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetUserByIdQuery();
            query.Id = (int)id;
            var User = await _mediator.Send(query);
            if (User == null)
            {
                return NotFound();
            }
            return View(User);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostDelete(int Id)
        {
            var command = new DeleteUserCommand();
            command.Id = Id;
            var query = new GetUserByIdQuery();
            query.Id = Id;
            var role = (await _mediator.Send(query)).Role;
            await _mediator.Send(command);

            return RedirectToAction(nameof(Index), new { role=role });

        }

        public async Task<IActionResult>Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetUserByIdQuery();
            query.Id = (int)id;
            var User = await _mediator.Send(query);
            if (User == null)
            {
                return NotFound();
            }
            ViewData["Role"] = new SelectList(Enum.GetValues(typeof(Role)));
            return View(User);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(User user)
        {
            var command = new UpdateUserCommand();
            command.User = user;
            await _mediator.Send(command);

            return RedirectToAction(nameof(Index),new {role=user.Role});
        }
        private async Task<bool> UserExists(int id)
        {
            var query = new GetUserByIdQuery();
            query.Id = id;
            if (await _mediator.Send(query) != null)
            {
                return true;
            }
            return false;
        }
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Shared/_Create.cshtml
@model EmployeeTask

<form method="post" asp-action="Create" id="taskForm">
    <div class="border p-3">
        <div class="mb-3 row">
            <h4 class="text-success">Tasks for this schedule:</h4>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="mb-3 form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Description"></label>
                    </div>
                </div>
                <div class="mb-3 form-group row">
                    <div class="col-6">
                        <input type="text" asp-for="Name" id="name" class="form-control" />
@*                        <span asp-validation-for="Name" class="text-danger"></span>*@
                    </div>
                    <div class="col-6">
                        <input type="text" asp-for="Description" id="description" class="form-control" />

@*                        <span asp-validation-for="Description" class="text-danger"></span>*@
                    </div>
                </div>
                <div class="mb-3 form-group row">
                    <div class="col">
                        <label asp-for="scheduledStart">Start Time</label>
                    </div>
                    <div class="col">
                        <label asp-for="scheduledStop">Stop Time</label>
                    </div>
                </div>
                <div class="mb-3 form-group row">
                    <div class="col">
                        <input type="datetime-local" id="scheduledStart" asp-for="scheduledStart" class="form-control"/>
@*                        <span asp-validation-for="scheduledStart" class="text-danger"></span>*@
                    </div>
                    <div class="col">
                        <input type="datetime-local" id="scheduledStop" asp-for="scheduledStop" class="form-control"/>
@*                        <span asp-validation-for="scheduledStop" class="text-danger"></span>*@
                    </div>
                </div>

                <div class="mb-3 form-group row">
                    <div class="col">
                        <label asp-for="Zone"></label>
                    </div>
                    <div class="col">
                        <label asp-for="Priority"></label>
                    </div>
                </div>
                <div class="mb-3 form-group row">
                    <div class="col">
                        <select asp-for="ZoneId" id="zone" class ="form-control" asp-items="@ViewBag.ZoneId"></select>
                    </div>
                    <div class="col">
                        <select asp-for="Priority" id="priority" class ="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(Priority)))"></select>
                    </div>
                </div>

                <div class="form-group row mt-3">    
                    <input type="button" id="taskbut" class="btn btn-block btn-outline-success" value="Add to Schedule"></input>
                </div>
            </div>
        </div>
    </div>
</form>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
$('#taskbut').click(function() {
    const Priority = {
	Low: 0,
	Medium: 1,
	High: 2,
    }
    var t = $("input[name='__RequestVerificationToken']").val();
    var task = {
        WorkScheduleId:null,
        Name: $('#name').val(),
        Description: $('#description').val(),
        scheduledStart: $('#scheduledStart').val(),
        scheduledStop: $('#scheduledStop').val(),
        ZoneId: parseInt($('#zone').val()),
        Priority:Priority[$('#priority').val()],
        Status:0
    };
    updateTasks(task)})

        
</script>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - ASP Groep L</title>   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" /> 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://groepltrees.web.app/ASP/images/ecology.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                        PlantIT Dashboard
                    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavDarkDropdown">
                   
                    @if(@User.Claims.Where(e=>e.Type=="http://schemas.microsoft.com/ws/2008/06/identity/claims/role").First().Value=="MVC Admin"){
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index" asp-route-role=@Role.Ionic_Employee>Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index" asp-route-role=@Role.MVC_Planner>Planners</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Zone" asp-action="Index">Zones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TreeSpecies" asp-action="Index">Tree Species</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Site" asp-action="Index">Sites</a>
                        </li>
                    </ul>
                    }        
                    else{
                    
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="WorkSchedule" asp-action="Index">Work Schedules</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="TreeSpecies" asp-action="Index">Tree Species</a>
                        </li>                       
                    </ul>
                    
                    
                    }
                    
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                            <li><a class="btn btn-outline-light" asp-controller="Account" asp-action="Profile">Hello @User.Identity.Name, @User.Claims.Where(e=>e.Type=="http://schemas.microsoft.com/ws/2008/06/identity/claims/role").First().Value</a></li>
                            <li><a class="btn btn-danger" id="qsLogoutBtn" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        }
                        else
                        {
                            <li><a class="btn btn-primary stretched-link" id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP Groep L - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>  
</html>