Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Controllers/ZoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.groep.L.Domain;
using ASP.groep.L.Infrastructure.Contexts;
using System.Diagnostics;
using MediatR;
using ASP.groep.L.Application.CQRS.Commands;
using ASP.groep.L.Application.CQRS.Queries;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace ASP.groep.L.Controllers
{
    [Authorize(Roles = "MVC Admin")]
    public class ZoneController : Controller
    {
        private IMediator _mediator;
        private IMapper _mapper;
        public ZoneController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(GetAllZonesQuery query)
        {
            return View(await _mediator.Send(query));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetZoneByIdQuery();
            query.Id = (int)id;
            var Zone = await _mediator.Send(query);
            if (Zone == null)
            {
                return NotFound();
            }

            return View(Zone);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["SiteId"] = new SelectList(await _mediator.Send(new GetAllSitesQuery()), "Id", "Name");
            ViewData["TreeSpeciesId"] = new SelectList(await _mediator.Send(new GetAllTreeSpeciesQuery()), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,SurfaceArea,SiteId,Site,TreeSpeciesId,TreeSpecies")] Zone Zone)
        {
            var treequery = new GetTreeSpeciesByIdQuery();
            treequery.Id = Zone.TreeSpeciesId;
            var tree = await _mediator.Send(treequery);
            var sitequery = new GetSiteByIdQuery();
            sitequery.Id = Zone.SiteId;
            var site = await _mediator.Send(sitequery);
            var command = new CreateZoneCommand();
            command.Zone = Zone;
            command.Zone.TreeSpecies = tree;
            command.Zone.Site = site;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id, GetZoneByIdQuery query)
        {
            if (id == null)
            {
                return NotFound();
            }

            query.Id = (int)id;
            var Zone = await _mediator.Send(query);
            ViewData["SiteId"] = new SelectList(await _mediator.Send(new GetAllSitesQuery()), "Id", "Name");
            ViewData["TreeSpeciesId"] = new SelectList(await _mediator.Send(new GetAllTreeSpeciesQuery()), "Id", "Name");
            return View(_mapper.Map<Zone>(Zone));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("Id,Name,Description,SurfaceArea,SiteId,TreeSpeciesId")] Zone Zone)
        {
            var treequery = new GetTreeSpeciesByIdQuery();
            treequery.Id = Zone.TreeSpeciesId;
            var tree = await _mediator.Send(treequery);
            var sitequery = new GetSiteByIdQuery();
            sitequery.Id = Zone.SiteId;
            var site = await _mediator.Send(sitequery);
            var command = new UpdateZoneCommand();
            command.Zone = Zone;
            command.Zone.TreeSpecies = tree;
            command.Zone.Site = site;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetZoneByIdQuery();
            query.Id = (int)id;
            var Zone = await _mediator.Send(query);
            if (Zone == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<Zone>(Zone));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            DeleteZoneCommand command = new DeleteZoneCommand();
            command.Id = id;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ZoneExists(int id)
        {
            if (id == null)
            {
                return false;
            }
            var query = new GetZoneByIdQuery();
            query.Id = id;
            var Zone = await _mediator.Send(query);
            if (Zone != null)
            {
                return true;
            }
            return false;
        }
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Zone/Create.cshtml
@model Zone

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div> ~ Voor informatie aan de developer*@
        <div class="mb-3 row">
            <h2 class="text-success">Add a Zone</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="SurfaceArea"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="SurfaceArea" class="form-control" />
                        <span asp-validation-for="SurfaceArea" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="TreeSpeciesId" class="control-label"></label>
                        <select asp-for="TreeSpeciesId" class ="form-control" asp-items="ViewBag.TreeSpeciesId"></select>
                    </div>
                    <div class="col-6">
                        <label asp-for="SiteId" class="control-label"></label>
                        <select asp-for="SiteId" class ="form-control" asp-items="ViewBag.SiteId"></select>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-success w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{ 
    @{ <partial name="_ValidationScriptsPartial" /> }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Zone/Delete.cshtml
@model Zone

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="mb-3 row">
            <h2 class="text-success">Delete a Zone</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="mb-3 row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Description"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-6">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                    <div class="col-6">
                        <input asp-for="Description" disabled class="form-control" />
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-success w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Zone/Details.cshtml
@model Zone

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Zone</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@Model?.Id">Update</a> |
    <a asp-action="Index">Back to List</a>
</div>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Zone/Index.cshtml
@model IEnumerable<Zone>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-success">Zones</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Zone" asp-action="Create" class="btn btn-outline-success">Add a new Zone</a>
        </div>
    </div>
    <br/>

    @if (Model.Count() > 0)
    {
            <table class="table table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>Zone ID</th>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var Zone in Model)
                {
                    <tr>
                        <td width="30%">@Zone.Id</td>
                        <td width="30%">@Zone.Name</td>
                        <td width="30%">@Zone.Description</td>
                        <td width="10%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="Zone" asp-action="Update" asp-route-Id="@Zone.Id" class="btn btn-success mx-1">Update</a>
                                <a asp-controller="Zone" asp-action="Details" asp-route-Id="@Zone.Id" class="btn btn-secondary mx-1">Details</a>
                                <a asp-controller="Zone" asp-action="Delete" asp-route-Id="@Zone.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
    }
    else
    {
       <p>No items created yet</p>
    }


</div>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/Zone/Update.cshtml
@model Zone

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="text-success">Update a Zone</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="SurfaceArea"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                    <input asp-for="SurfaceArea" class="form-control" />
                        <span asp-validation-for="SurfaceArea" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="TreeSpeciesId" class="control-label"></label>
                        <select asp-for="TreeSpeciesId" class ="form-control" asp-items="ViewBag.TreeSpeciesId"></select>
                    </div>
                    <div class="col-6">
                        <label asp-for="SiteId" class="control-label"></label>
                        <select asp-for="SiteId" class ="form-control" asp-items="ViewBag.SiteId"></select>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-success w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }