Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Controllers/WorkScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.groep.L.Domain;
using ASP.groep.L.Infrastructure.Contexts;
using System.Diagnostics;
using MediatR;
using ASP.groep.L.Application.CQRS.Commands;
using ASP.groep.L.Application.CQRS.Queries;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using ASP.groep.L.Application.CQRS.DTOS;

namespace ASP.groep.L.Controllers {
    [Authorize(Roles = "MVC Admin,MVC Planner")]
    public class WorkScheduleController : Controller
    {
        private IMediator _mediator;
        private IMapper _mapper;
        public WorkScheduleController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(GetAllWorkSchedulesQuery query)
        {
            return View(await _mediator.Send(query));
        }


        public async Task<IActionResult> Details(int? id)
        {
            var query = new GetWorkScheduleByIdQuery();
            query.Id = (int)id;
            var WorkSchedule = await _mediator.Send(query);

            return View(WorkSchedule);
        }
        public async Task<IActionResult> Tasks(int? id)
        {
            var query = new GetWorkScheduleByIdQuery();
            query.Id = (int)id;
            var WorkSchedule = await _mediator.Send(query);
            ViewData["Zone"] = new SelectList(await _mediator.Send(new GetAllZonesQuery()), "Id", "Name");
            var schedulequery = new GetAllEmployeeTasksByScheduleQuery();
            schedulequery.schedule = WorkSchedule;
            ViewData["EmployeeTasks"] = await _mediator.Send(schedulequery);
            return View(WorkSchedule);
        }
        public async Task<IActionResult> Create()
        {
            var users = await _mediator.Send(new GetAllUsersQuery());
            var zones = await _mediator.Send(new GetAllZonesQuery());
            ViewData["EmployeeId"] = new SelectList(users.Where<User>(u=>u.Role==Role.Ionic_Employee), "Id", "Fullname");
            ViewData["PlannerId"] = new SelectList(users.Where<User>(u => u.Role == Role.MVC_Planner), "Id", "Fullname");
            ViewData["ZoneId"] = new SelectList(zones, "Id","Name");
            return View(new WorkSchedule());
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody] WorkScheduleDTO schedule)
        {
            var WorkSchedule = _mapper.Map<WorkSchedule>(schedule);
            var command = new CreateWorkScheduleCommand();
            command.WorkSchedule = WorkSchedule;
            foreach (var task in command.WorkSchedule.EmployeeTasks)
            {
                var query = new GetZoneByIdQuery();
                query.Id = task.ZoneId;
                task.Zone = await _mediator.Send(query);
                task.WorkSchedule = command.WorkSchedule;
            }
            var t = _mapper.Map<WorkScheduleDTO>(await _mediator.Send(command));
            return Ok(t);
        }


        public async Task<IActionResult> Update(int? id,GetWorkScheduleByIdQuery query)
        {
            query.Id = (int)id;
            var WorkSchedule = await _mediator.Send(query);
            if (WorkSchedule == null)
            {
                return NotFound();
            }
            var users = await _mediator.Send(new GetAllUsersQuery());
            ViewData["EmployeeId"] = new SelectList(users.Where<User>(u => u.Role == Role.Ionic_Employee), "Id", "Fullname");
            ViewData["PlannerId"] = new SelectList(users.Where<User>(u => u.Role == Role.MVC_Planner), "Id", "Fullname");
            return View(WorkSchedule);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("Id,Description,Employee,Planner,EmployeeTasks,EmployeeId,PlannerId")] WorkSchedule WorkSchedule)
        {
            var command = new UpdateWorkScheduleCommand();
            command.WorkSchedule = WorkSchedule;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var query = new GetWorkScheduleByIdQuery();
            query.Id = (int)id;
            var WorkSchedule = await _mediator.Send(query);
            if (WorkSchedule == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<WorkSchedule>(WorkSchedule));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            DeleteWorkScheduleCommand command = new DeleteWorkScheduleCommand();
            command.Id = id;
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> WorkScheduleExists(int id)
        {
            if (id == null)
            {
                return false;
            }
            var query = new GetWorkScheduleByIdQuery();
            query.Id = id;
            var WorkSchedule = await _mediator.Send(query);
            if (WorkSchedule != null)
            {
                return true;
            }
            return false;
        }
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Create.cshtml
@model ASP.groep.L.Domain.WorkSchedule
    <div class="container">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@

        <div class="row">
                <div class="row">
                    <div class="col-sm">
                        <h2 class="text-success">Add a WorkSchedule</h2>
                        <div class="row">
                        <div class="col md-6">
                            <div class="row">
                                <input type="button" id="addScheduleBut" value = "Create" class="btn btn-outline-success btn-block">     
                            </div>
          
                        </div>
                        <div class="col md-6">
                            <div class="row">
                                <button asp-action="Index" type="button" class="btn btn-outline-danger btn-block">Back</button>
                            </div>
                        </div>
                    </div>

                </div>
                </div>
                <div class="row mt-2">
                    <div class="col-sm">
                        <label asp-for="Employee"></label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-sm">
                        <select asp-for="EmployeeId" id="employee" class ="form-control" asp-items="ViewBag.EmployeeId"></select>
                    </div>
                </div>

                <div class="row mt-2">
                    <div class="col-sm">
                        <label asp-for="Planner"></label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-sm">
                        <select asp-for="PlannerId" id="planner" class ="form-control" asp-items="ViewBag.PlannerId"></select>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-sm">
                        <label asp-for="Description"></label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-sm">
                        <input asp-for="Description" id="description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            @Html.Partial("Tasks",Model)
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
var $j = jQuery.noConflict();
var table = document.getElementById("tabletest")
var tasks = []
const Priority = {
    Low: 0,
    Medium: 1,
    High: 2,
}                

function addListeners(){
    let elList = Array.from(document.getElementsByClassName("btn btn-outline-danger removebut"))
    elList.forEach(el=>{
        el.addEventListener("click",()=>{
            tasks.splice(parseInt(el.name), 1)
            console.log("removing task")
            refreshTable()
        })
    })
}

function updateTasks(task){
    tasks.push(task)
    refreshTable()
    console.log(tasks)
}

function refreshTable(){
    let count = 0
    table.innerHTML = ``
    tasks.forEach(task=>{
    let actual
    if(task.actualStart!=null && task.actualStop!=null){
        actual = `<td width="15%">${task.actualStart} - ${task.actualStop}</td>`
    }
    else
    {
        actual = `<td width="15%">Not Completed Yet</td>`
    }
    table.innerHTML+=
    `<tr>
        <td>${task.Name}</td>
        <td>${task.scheduledStart} - ${task.scheduledStop}</td>`
        + actual+     
        `
        <td>${task.Priority}</td>
        <td>                          
            <button class="btn btn-outline-danger removebut" id="removebut" name="${count}">Remove From Schedule</button>
        </td>
        </tr>`
    count++;
})
addListeners()
$j.ajax({})
}


$("#addScheduleBut").click(async function (){
    var t = $("input[name='__RequestVerificationToken']").val();

        var schedule = {
            Description: $('#description').val(),
            PlannerId: parseInt($('#planner').val()),
            EmployeeId: parseInt($('#employee').val()),
            EmployeeTasks:tasks
        };
    
        $j.ajax({
            type: 'Post',
            url: '/WorkSchedule/Create',
            headers:
            {
                "RequestVerificationToken": t
            },
            data: JSON.stringify(schedule),
            contentType:'application/json; charset=utf-8;',
            success: function(suc) {
                var wsId = suc.id
                alert("Schedule Added Successfully")
                tasks.forEach(task=>{
                    console.log("posting task")
                    task.WorkScheduleId = wsId
                    $j.ajax({
                        type: 'Post',
                        url: '/EmployeeTask/Create',
                        headers:
                        {
                            "RequestVerificationToken": t
                        },
                        data: JSON.stringify(task),
                        contentType:'application/json; charset=utf-8;',
                        success: function(suc) {
                            console.log("success");                      
                        },
                        error: function(err) {

                            console.log(err)
                        }
                    })});
                window.location.href = "/WorkSchedule/Index"
            },
            error: function(err) {
                alert(err.responseJSON["Message"]);
            }
        });
    })
</script>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Delete.cshtml
@model ASP.groep.L.Domain.WorkSchedule

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="mb-3 row">
            <h2 class="text-success">Delete a WorkSchedule</h2>
        </div>
        <div class="row">
            <div class="col-12">

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Employee"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                        <input asp-for="Employee" disabled class="form-control" />
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Planner"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                        <input asp-for="Planner" disabled class="form-control" />
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Description"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                        <input asp-for="Description" disabled class="form-control" />
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-success w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Details.cshtml
@model WorkSchedule

@{
    ViewData["Title"] = "Details";
}

<h1>WorkSchedule Details</h1>

<div>
    <h4>Planner</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Planner)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Planner)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeTasks)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmployeeTasks)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Index.cshtml
@model IEnumerable<ASP.groep.L.Domain.WorkSchedule>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-success">WorkSchedules</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="WorkSchedule" asp-action="Create" class="btn btn-success">Add a new WorkSchedule</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Employee</th>
                    <th>Planner</th>
                    <th>Description</th>
                    <th>Changes</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var workSchedule in Model)
                {
                    <tr>
                        <td width="5%">@workSchedule.Id</td>
                        <td width="10%">@workSchedule.Employee.FirstName @workSchedule.Employee.LastName</td>
                        <td width="10%">@workSchedule.Planner.FirstName @workSchedule.Planner.LastName</td>
                        <td width="15%">@workSchedule.Description</td>
                        
                        <td width="20%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="WorkSchedule" asp-action="Update" asp-route-Id="@workSchedule.Id" class="btn btn-success mx-1">Update</a>
                                <a asp-controller="WorkSchedule" asp-action="Delete" asp-route-Id="@workSchedule.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No WorkSchedules created yet.</p>
    }


</div>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Tasks.cshtml
@model WorkSchedule


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            @if (@Model.Employee!= null)
            {
                <h2 class="text-success">@Model.Employee.Fullname Task List</h2>
            }

        </div>
        @{
            var t = new EmployeeTask();
        }
        @Html.Partial("_Create",t)
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Scheduled</th>
                    <th>Actual</th>
                    <th>Priority</th>
                </tr>
            </thead>
            <tbody id="tabletest">
            </tbody>
        </table>
    </div>

    <br />
</div>

Frontend MVC/ASP.groep.L/ASP.groep.L.MVC/Views/WorkSchedule/Update.cshtml
@model ASP.groep.L.Domain.WorkSchedule

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="text-success">Update a WorkSchedule</h2>
        </div>
        <div class="row">
            <div class="col-12">

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Employee"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                           <label asp-for="EmployeeId" class="control-label"></label>
                        <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.EmployeeId"></select>
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Planner"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                           <label asp-for="PlannerId" class="control-label"></label>
                        <select asp-for="PlannerId" class ="form-control" asp-items="ViewBag.PlannerId"></select>
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-12">
                        <label asp-for="Description"></label>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-12">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-outline-success w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-outline-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}